### ISSUE TITLE
1. NMMNH Birds - Manage Collection

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#1]
Follow instructions at [How to Manage a Collection](http://handbook.arctosdb.org/how_to/How-to-Manage-a-Collection-in-Arctos.html)

**Comment by lin-fred** [comment]
How is the contact usually divided out. Do i put my name for both the data quality and loans? or our registrar for loans? Am i able to put two people down for loans?

**Comment by dustymc** [comment]
There are no technical limitations - any Operator can act in any number of roles, and any role can have any number of contacts.

**Comment by lin-fred** [comment]
Thanks. Can the head image/color and other institution urls be updated later without breaking anything? We plan to update our collected web pages, but that may take some time, so when it does get updated can we update the urls then?

**Comment by dustymc** [comment]
Yes, you can update most anything at any time.

**Comment by lin-fred** [comment]
I've been trying to update the Agents, and in using the Agent Namestring Formatter trying to see what needs to be updated because I know I'm going to have quite a few of the same agents that are already in Arctos, but a majority that will not be. I can't seem to understand how to use it? Is is better to check agents one by one?

**Comment by Jegelewicz** [comment]
@dustymc how difficult would it be to create a tool similar to the scientific name checker, but for agents. Something that would just say - yep that agent exists, it's possible that agent exists (and this is who we think it might be), or I don't see that agent in Arctos yet?

**Comment by dustymc** [comment]
The agent bulkloader does that, except it's "here's some similar data that might refer to the same entity" rather than a definitive match.

**Comment by lin-fred** [comment]
Thank you Dusty, your information was what I was thinking of. 

I tried a list and I have a few questions. Attached is a screen capture of some of the data. This is indicating that Michael Sanchez and Myron Chase are possibly duplicates (and therefore I will look into those two personally), but the rest of the people can probably be uploaded without creating a duplicate? Is this the correct assumption?
![AgentBulkload](https://user-images.githubusercontent.com/19802479/54947122-35568380-4eff-11e9-8270-ddc4175f9d48.PNG)

**Comment by lin-fred** [comment]
And of course getting rid of the duplicates, like the Phil at the bottom..

**Comment by dustymc** [comment]
Yep, that should be sufficient.

If Myron Chase is (or reasonably could be) http://arctos.database.museum/agent.cfm?agent_id=21282663&agent_name=Myron%20Chase then you can just delete that from your agent data - your specimens will already load (under the shared agent record, which might be linked to field notes and such). It it's a different person, http://handbook.arctosdb.org/documentation/agent.html#different-agent-same-name

Yes please merge Phil[lip] if possible. Some of those will probably slip through anyway, http://handbook.arctosdb.org/documentation/agent.html#deletingmerging-agents is how to deal with them when you find them.

And please let me know if you do manage to create any duplicates that you think should have been detected - I can use that to make the tools "smarter."

**Comment by Jegelewicz** [comment]
Added Dusty as technical support contact.

**Comment by Jegelewicz** [comment]
Completed with logo.
