### ISSUE TITLE
3. NMMNH Inv - Agents

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#12]
Read the documentation about [Agents](http://handbook.arctosdb.org/documentation/agent.html).

Create a list of people included in the data to be migrated in a .csv file (Excel will work fine for this). Look in fields where you store the names of collectors, preparators, donors, publication authors, etc.

Review the list for alternate spellings and versions of "unknown" (names that are only initials or include only initials plus last name). Try to make each name as complete as possible and to ensure that there are no duplicates. Don't lose the original spellings/abbreviations as you will need to ensure they are either part of an Agent or are modified in your data to match an Agent name before you load your data.

Use the csv in the Agent BUlkload tool to find out which names in your list need to be added to Arctos Agents.

from the Arctos main menu select Enter Data > Batch Tools > Bulkload Agents and follow the instructions

**Comment by lin-fred** [comment]
I have a batch of agents from our invertebrates ready to upload. Let me know when someone is available so I can send along the file. Thanks.

**Comment by Jegelewicz** [comment]
@lin-fred you can send it to me by email.

**Comment by lin-fred** [comment]
The only email I have for you is the Arctos Treasurer one, so I sent it there but let me know if there is any other one you want me to use for this instead. Thanks!

**Comment by Jegelewicz** [comment]
That's perfect - I'll take a look at it tomorrow. Thanks!

**Comment by Jegelewicz** [comment]
These Agents have been added. These were already in Arctos:

Boyles, J. M.
Burch, J. Q.
Chermock, R. L.
Coultas, W. F.
Bronson, A. B.

So they may or may not be different people. If you can find any way to distinguish your Bronson, A. B. from the Bronson, A. B. added by Denver Inverts (hey, it probably is the same person!), then you should create a new agent and use it instead of the one that is already there. Otherwise, you should be good to go!

**Comment by lin-fred** [comment]
But I probably won't be able to tell that they are the same person unless I find the persons contact information? Isn't the safer route creating a new agent, and then merging them later when, and if, I find they are the same person?

**Comment by dustymc** [comment]
I'd always err on the side of fewer agents. Overloaded agents are much easier to detect than duplicates, and it's easy to split them if you come to know more.

**Comment by lin-fred** [comment]
So its better to split than to merge?

**Comment by dustymc** [comment]
Well neither are ideal! My suggestion is that you use the existing agents unless you have some evidence that they're not the same. If you do, you should also create 'not the same as' relationships and leave remarks (unless the reasoning is evident from other data - eg, birth dates).

**Comment by Jegelewicz** [comment]
> Isn't the safer route creating a new agent, and then merging them later when, and if, I find they are the same person?

Agents with EXACTLY the same name are not allowed, so unless you have something other than Bronson, A. B., there is no way to "split" agents. There is no "safe" when you don't have more specific information. If at some point you discover that your Bronson, A. B. is Arthur B. Bronson, then at that time you can create his Agent name and change the collectors, identifiers, etc. in your records to his name instead. (Sounds daunting, but can be done without too much fuss - potentially with a little help from Dusty, but probably all on your own!)

**Comment by dustymc** [comment]
> If at some point you discover that your Bronson, A. B. is Arthur B. Bronson, then at that time you can create his Agent name and change the collectors, identifiers, etc. in....

Most of the time it seems to turn out that they're all Arthur B., so when you find and add information you'll make everyone's data better. The context in Arctos is hugely helpful for this - eg, I've figured out a ton of stuff in incoming collections by looking at MVZ's egg slips, which can be difficult to find when you're cleaning up your initial import but are easily accessible once your specimens are sharing information with other collections.

And yes, we can certainly help if you find yourself with a problem of any sort that can't be easily addressed from the forms.

**Comment by lin-fred** [comment]
Thanks! This is clearer now and makes sense.

**Comment by lin-fred** [comment]
I'm looking to upload an agent but not sure how it should go:

Ball, G.E.

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/agent.html#creating--maintaining-agents

http://arctos.database.museum/agents.cfm?agent_id=21253088 - you can just use that if it might be the same agent, and please leave relationships and remarks if it's not.

**Comment by lin-fred** [comment]
I have an agent that is the National Museum of Victoria, but it doesn't seem to be a current entity anymore: https://en.wikipedia.org/wiki/Museums_Victoria
What should I do?

**Comment by dustymc** [comment]
This? https://arctos.database.museum/agents.cfm?agent_id=21319422

If so, add AKAs as necessary. 

If not, make a new agent with, I suppose, a "dead" status, and perhaps a relationship to 21319422 if that's where the collections are now or similar.

If they've just changed the name then it's (probably) one Agent, if there's been some sort of reorganization-or-whatever then maybe multiple agents is better (eg, more useful when trying to track down more data and such). If you don't have enough information to know - pick one and hope....

**Comment by lin-fred** [comment]
For Schalie Van der ... I have a "Van der Schalie, H."

Same person do we think? @Jegelewicz

**Comment by Jegelewicz** [comment]
Probably - we created that agent, so I say you edit it to include both variations.
