### ISSUE TITLE
3. NMMNH Ento - Agents

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#13]
Read the documentation about [Agents](http://handbook.arctosdb.org/documentation/agent.html).

Create a list of people included in the data to be migrated in a .csv file (Excel will work fine for this). Look in fields where you store the names of collectors, preparators, donors, publication authors, etc.

Review the list for alternate spellings and versions of "unknown" (names that are only initials or include only initials plus last name). Try to make each name as complete as possible and to ensure that there are no duplicates. Don't lose the original spellings/abbreviations as you will need to ensure they are either part of an Agent or are modified in your data to match an Agent name before you load your data.

Use the csv in the Agent BUlkload tool to find out which names in your list need to be added to Arctos Agents.

from the Arctos main menu select Enter Data > Batch Tools > Bulkload Agents and follow the instructions

**Comment by lin-fred** [comment]
Sent the agent list to Teresa for upload

**Comment by Jegelewicz** [comment]
@lin-fred these are in. There is one name that might be a duplicate:

> Kim Score

There was already a Kimberly Score in Arctos who collected a couple of snails that are at UTEP in the late 1990's. Is it possible your Kim Score is the same person?

**Comment by lin-fred** [comment]
I would definitely say its possible, good catch on that one

**Comment by Jegelewicz** [comment]
Cool. If you determine they are the same, just add the relationship "bad duplicate of" Kimberly Score to the agent record for Kim Score. Let me know if that makes no sense!
