### ISSUE TITLE
NMMNH Paleo - landstat

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#131]
Treatment of this field:

This will become the "Site Land Status" locality attribute (via Geology) with anything in the statmap field in the remarks of the associated attribute.

**Comment by Jegelewicz** [comment]
Currently landstat contains almost 200 unique terms. I suggest we consolidate these as shown in the attached file. This will consolidate terms to fewer than 20.

@Nicole-Ridgwell-NMMNHS I need your input on terms at the bottom. Also, should we stick with "Indian" or change all of these to "Indigenous" or some other term?
[landstat.xlsx](https://github.com/ArctosDB/data-migration/files/3745129/landstat.xlsx)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
From looking around on various government websites, I believe the term to use will be Tribal. Also, I think some of the terms currently in remarks can be moved to higher geography (the pueblos, White Sands MR, etc.). I think this a good consolidation.

We could probably use this article for the Land Grant definition: https://en.wikipedia.org/wiki/Land_grants_in_New_Mexico

I added few things at the bottom, but I think most of the odd ones will have to go into remarks for now until we suss out what they should actually be.

[landstat.xlsx](https://github.com/ArctosDB/data-migration/files/3745307/landstat.xlsx)

**Comment by Jegelewicz** [comment]
/remind me to do this on Monday

**Comment by Jegelewicz** [comment]
Changed "Indian" to "Tribal"

Added


Bankhead-Jones Land Use Lands
City
County
DOD
DOE
NPS
NWR
Public
USACE
USFWS

Will change data before upload to Arctos based upon landstat file.
