### ISSUE TITLE
Get documentation in the right folder

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#139]
@anna-chinn can you edit this? t needs to be moved to the How To folder. If you edit the file name so that it is /_how_to/ Create How-To-Use-Complex-Identifications-As-Low-Quality-Data-Flags.markdown I think that will get it where it should be.

![image](https://user-images.githubusercontent.com/5725767/67326382-b3016280-f4d3-11e9-9963-8a36d7f1dcd4.png)

**Comment by anna-chinn** [comment]
I think that's where it is (or at least how it looks on my end). This is the directory that it's in now: https://github.com/ArctosDB/documentation-wiki/tree/gh-pages/_how_to

**Comment by Jegelewicz** [comment]
Check! Thanks!
