### ISSUE TITLE
NMMNH Dates

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#140]
I asked Dusty about dates and he says you can put just yyyy or yyyy-mm in the MADE_DATE and SPECIMEN_EVENT_DATE.

See  http://handbook.arctosdb.org/documentation/dates.html (read it just for the cartoon and the dry Dusty-speak - I'm pretty sure Bill Gates doesn't personally hate you...)

Of course for BEGAN and ENDED dates, we should still make the adjustments, but for MADE_DATE and SPECIMEN_EVENT_DATE we should be able to use the abbreviated date. Let me know if any of you tries this!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Excellent!

**Comment by dustymc** [comment]
>SPECIMEN_EVENT_DATE

Sorta...

ASSIGNED_DATE is a DATE object, VERIFIED_DATE is ISO8601.

**Comment by Jegelewicz** [comment]
> We have been trying to develop a system for entering specimens with missing dates into Arctos. For those missing a collection date we have been using 1800-01-01 with a note that this date has been interpreted so it could be entered into Arctos. If they have a preparation date we have been using that as the end date. However, in our data sheet, for some of the specimens that only have a prep date have it also listed as the collection date. We know this is erroneous because specimens generally need to be frozen before they're prepared, but we're not entirely sure how to resolve this inconsistency. Do you think it would be better to use our default unknown date "1800-01-01", or use the one date we have which we know is not exact but is probably more accurate?

@PaulaBarteau If everything with the 1800-01-01 AND "no date" in the verbatim date need research, that is a great way to leave yourself a list of things that need work. For now, I think using the default date makes sense. It is possible that information could turn up that will help you figure some of these out.

When you know the prep date, use the specimen attribute "verbatim preservation date" and put the date in there, even for stuff with a known collection date this can be very useful information about how long the animal sat in the freezer before it was prepped.

**Comment by Jegelewicz** [comment]
Actually, after going through some old issues, instead of verbatim preservation date, what we should do is add a preservation attribute to the part (or parts).

So for a bird with a study skin and skeleton where the preparation date and preparator are known, you would have:

skin, study

with the part attribute

part_attribute | part_attribute_value | part_attr_det_date | part_attribute_determiner
--- | --- | --- | ---
preservation | dry | yyyy-mm-dd | preparator name

**Comment by PaulaBarteau** [comment]
For attributes, Arctos requires a date so we've been entering the pro date
if we have it, but for Parts we haven't and they generally refer to prep
date in the attributes field. We have improved our dating flowchart process
somewhat this morning.

Are you saying I should put the preparation date in the Part Remark field?

Thanks,
Paula

**Comment by Jegelewicz** [comment]
> Are you saying I should put the preparation date in the Part Remark field?

Demonstrated part attribute via "add parts" in data entry.
Resolved and documented

**Comment by lin-fred** [comment]
Can I get some clarification on MADE_DATE

https://handbook.arctosdb.org/documentation/bulkloader.html and the bulkload builder indicates it's required.  Is it required to be in the bulkload, but it doesn't have to be filled out?

**Comment by Jegelewicz** [comment]
Leave one blank - it should load because it isn't required.

**Comment by lin-fred** [comment]
Documentation needs to be updated. We've been uploading our data with Made Date being the collection date or our 1800-01-01 thinking it was required

Also, it seems its the only Field that is required for bulkloading but can be uploaded without information in it, but no documentation indicates it can be null.

**Comment by lin-fred** [comment]
Can't add documentation label because this is in data migration?

**Comment by Jegelewicz** [comment]
I added it to the documentation wiki issues.
