### ISSUE TITLE
NMMNH- Arsenic Specimen Preparation Denotation

### ISSUE THREAD

**Issue by PaulaBarteau** [ArctosDB/data-migration#141]
Hello,
I am migrating data for our bird collection into Arctos and have encountered a group of specimens prepared with arsenic. What is the formal denotation for this kind of preparation? There isn't a specific value for this kind of preparation in the Part Name field, so I am assuming it would go in the Part Name Remarks field, but I wanted to ask if there is a standard practice for entering these kinds of specimens. They are all Mounted Taxidermy specimens.
Thanks you for your time,
Paula

**Comment by Jegelewicz** [comment]
@PaulaBarteau I think we should set up a new preservation method = "arsenic", do you have any details about the arsenic preparation other than "arsenic"?

**Comment by campmlc** [comment]
Use of arsenic in taxidermy and specimen preparation for bird and mammal
skins used to be common.I added it and some reference material to the code
table.
Marte, F., A. Péquignot, D. W. V. Endt. 2006. Arsenic in taxidermy
collections: history, detection, and management. Collection Forum, 21(1-2),
143-150

**Comment by PaulaBarteau** [comment]
@campmlc  Thank you!
