### ISSUE TITLE
NMMNH - Prep date herbarium

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/data-migration#150]
I have recorded prep dates for many of our herbarium specimens. I don't have any attribute data that it can be attached to. Where should it go?

**Comment by dustymc** [comment]
Attribute "verbatim preservation date" exists and is probably aimed at about the same thing. Adding a specimen-event might be better, but I doubt if this justified the work.

**Comment by Jegelewicz** [comment]
What Dusty said - use "verbatim preservation date" with the preparator name as the determiner and the preservation date as the value and determination date. You could also add an attribute remark like "date specimen was prepared" to clarify.

**Comment by lin-fred** [comment]
I don't see this option in the herbarium data entry screen, and on the code table it says its not listed for herbarium
![image](https://user-images.githubusercontent.com/19802479/68885918-4ee94d00-06d3-11ea-8693-829ce54b26df.png)

**Comment by Jegelewicz** [comment]
Ah ha! it should be available now!
