### ISSUE TITLE
ASNHC:Mamm - Bulkload Specimens (Parts)

### ISSUE THREAD

**Issue by snknts** [ArctosDB/data-migration#157]
@dustymc , @Jegelewicz :

@diannakrejsa  and I finished our first stage of specimen loads.. and are 1200 deep into their corresponding parts.
and...
we just realized we've been doing the wrong part type (we're using "skin" and we should be using "skin, study".

Question:
What's the best way to correct these?  
 Can you run a SQL update for us? (or can we?)
 Is there a bulk.. updater or deleter for parts? 
If updating them isn't an option.. can you/we just remove all the parts and we load fixed CSV files?
(Reloading them 500 at a time is faster than correcting them one at a time)

Please advise :)

**Comment by snknts** [comment]
put wrong numbers in last night.. it's 2500ish parts.. 1200ish of which have the wrong type.

**Comment by Jegelewicz** [comment]
Done - You can use "Modify Parts" once you have searched for the appropriate records (took me a whole 5 minutes...) 
<img width="960" alt="Screenshot 2019-11-26 09 10 44" src="https://user-images.githubusercontent.com/5725767/69651217-fc8e2180-102c-11ea-8ba5-182346bc83a9.png">

**Comment by snknts** [comment]
that was exactly what I was looking for.  Thank you :)
