### ISSUE TITLE
ASNHC:Mamm - Bulkload Specimens - Collector

### ISSUE THREAD

**Issue by snknts** [ArctosDB/data-migration#165]
@diannakrejsa and I are bulkloading agents (preparators).. and it 
doesn't seem to like agent names with apostrophe's in them
(C. E. O'Dowd specifically)
It worked in the bulk load specimens tool with that character.. but not here.

Help!  what do we need to do/change to get it loaded here too?

**Comment by snknts** [comment]
suspect you maybe missed this.  We also got some unique constraints (and partial loads)
unique constraint (UAM.IX_COLLECTOR_COID_AID_ROLE) violated.

trying to assign the same agent multiple times to an item/part maybe?

**Comment by snknts** [comment]
looping in :P@Jegelewicz

**Comment by snknts** [comment]
@Jegelewicz , @dustymc 
I didn't do that right... finals week is taking its toll

**Comment by Jegelewicz** [comment]
Somehow I did miss it!

[C. E. O'Dowd](http://arctos.database.museum/agents.cfm?agent_id=21324612) is already in the agent table and you cannot load duplicate agents to the table. You can use that name as either a collector or preparator or in any other "Agent" role. Let me know if this doesn't answer that question!

> We also got some unique constraints (and partial loads) unique constraint (UAM.IX_COLLECTOR_COID_AID_ROLE) violated. trying to assign the same agent multiple times to an item/part maybe?

That's probably it, but I'd have to see the data to be sure. If you try to load an agent name along with the same role twice for a single record that's a violation! You can load the same agent name with two different roles though (C. E. O'Dowd can be "collector" and "preparator" for a single record, but NOT "collector" and "collector"). Check your data for something like that.

Let me know if this doesn't help!

**Comment by snknts** [comment]
the unique contrants was that.. bug in my exporter.. sigh..

The agent problem is slightly different then that.

We're bulk loading collectors.  they've all loaded except those with an ' in their agent name

here's a simple file:
guid,other_id_type,other_id_number,agent_name,COLL_ORDER,COLLECTOR_ROLE
ASNHC:Mamm:5809,preparator number,CED 5,C. E. O'Dowd,1,preparator

it fails (agent not found)  because of the '  it seems.
(does that make sense?)

**Comment by Jegelewicz** [comment]
Yep - Here is a solution, maybe not THE solution but one that should work for now.

Make sure that the Agent has the aka C. E. ODowd (no apostrophe), then change all of the C. E. O'Dowd in your bulkload file to C. E. ODowd. That should load them, but they should appear in the records as C. E. O'Dowd (the preferred name is what shows up everywhere).

@dustymc agree?

**Comment by campmlc** [comment]
That sounds like it would work. But do we have any alternative for dealing
with these characters? @Dusty <dustymc@gmail.com>  ?

**Comment by dustymc** [comment]
I need the file that caused the issue before I can say anything.

**Comment by snknts** [comment]
I'll zip and attach:
[mammalogy-Preparators-cleaned.01.zip](https://github.com/ArctosDB/data-migration/files/3951370/mammalogy-Preparators-cleaned.01.zip)
hopefully that worked... my wm doesn't have a native file manager...
(linux geek)

**Comment by dustymc** [comment]
patched

**Comment by snknts** [comment]
it works.  thanks :)
