### ISSUE TITLE
Adding Geology Attributes to Code Table

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/data-migration#177]
I need to add some new formations to the Geology Code Table:

Lower Gosport Sand
Upper Lisbon Formation
Tallahatta-Lisbon Contact

**Comment by campmlc** [comment]
Arctos has
Gosport Sand: https://en.wikipedia.org/wiki/Gosport_Sand
Lisbon Formation: https://en.wikipedia.org/wiki/Lisbon_Formation
Tallahatta Formation: https://en.wikipedia.org/wiki/Tallahatta_Formation
We are trying to limit the code table to entries that have a reference or
wikipedia entry for verification.
@Teresa Mayfield <jegelewicz66@gmail.com> @Dustin Perriguey
<dperriguey@unm.edu>  what would be the best way to add the qualifiers
Upper, Lower, or Contact?

**Comment by dustymc** [comment]
> best way to add the qualifiers Upper, Lower, or Contact?

Formation-->member-->bed is the formal division. Anything else should be entered as remarks.

**Comment by Jegelewicz** [comment]
Put upper and lower in the geology attribute remark.

**Comment by Jegelewicz** [comment]
for Tallahatta-Lisbon Contact add both geology attributes:

Tallahatta Formation
Lisbon Formation

then put "Tallahatta-Lisbon Contact" in the remarks for both.

**Comment by mbprondzinski** [comment]
All right.
