### ISSUE TITLE
Easy way to know what the last catalog number was entered by Arctos within a particular collection?

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/data-migration#178]

**Comment by Jegelewicz** [comment]
Reports/Services>Catalog Number Gaps - the last number will be the last number in Arctos.

**Comment by mbprondzinski** [comment]
Yes, thanks, I found that.  However, it took me another 15 minutes to find where I stumbled on that menu item, and if I could “Save” it as a Search, it would be extremely helpful.  I need to keep going back to the last entered record to make sure everything is as it should be and I have no idea what the catalog number is or how to easily find it.  There are too many menu items to remember where they are all hidden (!)

**Comment by Jegelewicz** [comment]
Bookmark this web address in your browser and label it "Find last catalog number".

https://arctos.database.museum/tools/findGap.cfm

**Comment by mbprondzinski** [comment]
Ok, I did that.  I just hope I can remember that I did that (!)  Thanks...
