### ISSUE TITLE
ALMNH Removing Field Columns in Search list

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/data-migration#187]
Is there a way to remove the "coordinates" columns or other unwanted "standard" fields?  Also, is there a way to move columns around after a search to bring the fields being used closer to each other?

Thanks!

**Comment by dustymc** [comment]
>remove

right-click the header

>move

No, but you can download.

**Comment by mbprondzinski** [comment]
Well, well, well, I've never seen that little list of the standard column headers pop into the screen!  It must appear down below the list of search records, which is why it hasn't been visible when I've tried clicking on the column headers before! Glad I was finally able to discover that...
