### ISSUE TITLE
JSNM - Media

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#191]
nor do I have access to media, which I will need at some point since we have images we want to attach. Is there a way I can get access to these features?

_Originally posted by @cefilipek in https://github.com/ArctosDB/data-migration/issues/189#issuecomment-576796534_

**Comment by Jegelewicz** [comment]
@cefilipek for media, I'd like you to read documentation first as this is a shared area of Arctos.

Start here: [What is Media in Arctos?](http://handbook.arctosdb.org/documentation/media.html)
then read [How to Upload Media to TACC](http://handbook.arctosdb.org/how_to/How-to-Upload-Media-to-TACC.html)

**Comment by Jegelewicz** [comment]
@ccicero What do we need to do to give Colleen the ability to add media at TACC?

**Comment by cefilipek** [comment]
@Jegelewicz Thanks! I've read the documentation, so I'm prepared once we figure this out.

**Comment by Jegelewicz** [comment]
OK - I gave you media access. See if you can load an image then we'll know if we need to get Carla to set you up.

**Comment by cefilipek** [comment]
I was able to upload the pictures of my object! Thanks!

**Comment by Jegelewicz** [comment]
Great! Just let me know if you have any questions.
