### ISSUE TITLE
NMMNH Paleo - Site numbers

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#192]
@Nicole-Ridgwell-NMMNHS I'm working up the list of site identifiers for the code table. Can you tell me what these acronyms stand for?

BUNM
NMBM
NMBMMR
SMP
UALP
UNM (University of New Mexico?)
USNM (Smithsonian?)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
BUNM - I have tried and failed to figure this one out in the past. I'm pretty sure it's something UNM, but I'm not sure. I'll email Spencer about it.

NMBM and NMBMMR - New Mexico Bureau of Mines and Mineral Resources (now the New Mexico Bureau of Geology and Mineral Resources)

SMP I need to research

UALP - University of Arizona Laboratory of Paleontology

Yes, UNM is University of New Mexico

Yes, USNM is the Smithsonian. Smithsonian used to be the United States National Museum and the National Museum of Natural History still uses USNM in their numbers.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
BUNM is BLM fossils at UNM

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
SMP is probably State Museum of Pennsylvania, that is where Bob Sullivan used to work.
