### ISSUE TITLE
1. NMMNH Paleo - Manage Collection

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#2]
Follow instructions at [How to Manage a Collection](http://handbook.arctosdb.org/how_to/How-to-Manage-a-Collection-in-Arctos.html)

**Comment by Jegelewicz** [comment]
Added Dusty as tech support contact

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Added myself as a contact, added citation information
