### ISSUE TITLE
user account issues

### ISSUE THREAD

**Issue by snknts** [ArctosDB/data-migration#200]
I changed my password today... and seemed to have locked my account somehow...
( joey76909 is my username in arctos )
...

HELP! ;)
@Jegelewicz

**Comment by snknts** [comment]
@dustymc 
@diannakrejsa 

(adding more for increased help :)

**Comment by Jegelewicz** [comment]
Just reset you - you should get an email from Arctos requiring you to reset your password.

**Comment by snknts** [comment]
I got he email.  thanks :)
