### ISSUE TITLE
NMMNH TRS Problems

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#201]
@Nicole-Ridgwell-NMMNHS I have placed an Excel workbook in N:\GeoScience\Arctos\Nicole\TRS Problems.xlsx that includes problematic townships, ranges, sections and aliquots. These will need to be corrected before I can enter the locality attributes for the affected localities.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Finished.

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS you asked to add a bunch of sections to the code table, but I can't figure out why there should ever be a section number greater than 36.

According to http://www.jsu.edu/dept/geography/mhill/phygeogone/trprac.html

> Townships are subdivided into SECTIONS. Since each township is six miles by six miles, township contains 36 square miles, each one forming a section. These are identified with a number based on their position. The northeasternmost section is section 1. They are numbered to the west in this northernmost row. The northwesternmost section in the township is section 6. Below it in the second row is section 7. This row is numbered toward the east. This snakelike pattern is continued so that the southwesternmost section is section 31 and the southeasternmost section is section 36. Note that to the east of section 36 will be section 31 of the next range but same township, and to the south of section 36 will be section 1 of the next township but the same range.

Of course it also says this:

> TOWNSHIP measures the distance NORTH or SOUTH from the BASE LINE which is a designated parallel. A township **USUALLY** measures SIX MILES in size. The first six miles north of the base line is township one north written T. 1 N., running from 0 to 6 miles north of the base line. T. 4. S. would, therefore, be 18 to 24 miles south of the base line. RANGE measures EAST or WEST from the PRINCIPAL MERIDIAN which is a designated meridian. Ranges are also **USUALLY** SIX MILES in size. The first six miles west of the principal meridian would be range one west, R. 1 W.. R. 3 E. would be 12 to 18 miles east of the principal meridian. Each square, six miles by six miles is called a township.

So these townships or ranges are bigger than 6X6? Just want to make sure we don't introduce anything odd to the code tables

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
No, there should not be section numbers larger than 36. However, townships and ranges can be above 36.

**Comment by Jegelewicz** [comment]
My bad - meant townships and ranges. Just wanted to make sure before I add stuff.

**Comment by Jegelewicz** [comment]
@Jegelewicz to add townships and ranges once Arctos is up.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Appreciate you making sure! The jumble of coordinate systems within coordinate systems that is TRS can definitely get confusing at times. A township is 6 mi x 6 mi and divided into 36 sections. Each TRS region is filled with a grid of these townships. The grid itself has a coordinate system. The north south coordinate is also called the "township", the east west coordinate is the range. So each unit of the coordinate is six miles long, but the number of coordinate units is only limited by the size of the TRS region and the position of the N-S and E-W baselines.

**Comment by Jegelewicz** [comment]
Added needed townships and ranges.

@Nicole-Ridgwell-NMMNHS locality 5799 still has a problem. Range says R30R - is is east or west?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
east
