### ISSUE TITLE
BYU Mammals, Birds, Fish - Create Collection

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#204]
Request from BYU to create mammal collection received 2020-01-28.

**Comment by Jegelewicz** [comment]
@dustymc BYU wants to add mammals, birds and fish - should I just change the status of [their prospective collection request](https://arctos.database.museum/new_collection.cfm?action=manage&id=E5D097359F0659DA9200449B2F9DBD0E) to new and add these or should I start up a new request?

**Comment by dustymc** [comment]
Ask @lkvoong but I think either is OK - AFAIK she just needs the data and can deal with status-and-such being weird or whatever.

Also: what's the urgency? Waiting for PG would be moderately useful - we have to rebuild the VPD on new collections, but there are some others and we have to do that anyway so whatever.

**Comment by Jegelewicz** [comment]
@byuherpetology I will need collection descriptions for mammals, birds and fish.

For reference, the description given for herps was:

> The BYU herpetology collection houses over 40,000 fluid preserved specimens, including 36 types, and over 15,000 tissue samples.  The geographic focus of the collection is the Great Basin/Intermountain West, but there are also extensive collections from Latin America, Central Africa, and the Pacific.

Also, just want to make sure that the following are all OK:

Catalog numbers will be integers
License should be Arctos data license and use

Thanks!

**Comment by Jegelewicz** [comment]
@lkvoong I just added the new collections to the old request - still need info from the institution. Will let you know when they are ready to go.

**Comment by byuherpetology** [comment]
Here are collection descriptions for BYU fish, bird and mammal collections.  Catalog numbers will be integers, and License should be Arctos data license and use.

Thank you 

Alison Whiting
Adjunct faculty and Curator of Herpetology
Brigham Young University

**Comment by Jegelewicz** [comment]
@byuherpetology I don't see the descriptions. Can you re-post?

**Comment by byuherpetology** [comment]
[Fish, Bird and Mammal Collection Summaries.docx](https://github.com/ArctosDB/data-migration/files/4162414/Fish.Bird.and.Mammal.Collection.Summaries.docx)
lets try that

**Comment by Jegelewicz** [comment]
[Approved to create collections](https://arctos.database.museum/new_collection.cfm?action=manage&id=E5D097359F0659DA9200449B2F9DBD0E)

@lkvoong please ignore the BYU:Herp collection as it already exists.

**Comment by lkvoong** [comment]
Hi Teresa,

I created three new BYU collections and added them to the public institution portal:

BYU:Mamm - http://arctos.database.museum/byu_mamm
BYU:Bird - http://arctos.database.museum/byu_bird
BYU:Fish - http://arctos.database.museum/byu_fish

The institution portal (http://arctos.database.museum/byu_all) now has access to the three new collections, as well as the existing BYU:Herp collection.

Access was granted to alisonwhiting (Alison) and jegelewicz (Teresa).

Please ask Alison to log in and update the collection profiles, if necessary.

Thanks!

**Comment by Jegelewicz** [comment]
Thanks a million!!
