### ISSUE TITLE
NMMNH Paleo - Jackets

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#212]
@Nicole-Ridgwell-NMMNHS I am working on locality L-3845 and many of the records have what appear to be jacket numbers in the remarks field. I can put these in collection object remarks, but I wonder if we should create a new type of [other ID](https://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLL_OTHER_ID_TYPE).

field jacket number - identifier assigned to a a plaster covering placed over and around a fossil or fossils, while in the field, to protect the fossil as it is removed and transferred safely back to the lab or museum for further study.

This would make finding stuff from the same jacket easier...

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Yes, this is a good idea. Field jacket numbers are a common practice in paleo, particularly for multi-jacket quarry sites.

**Comment by Jegelewicz** [comment]
Added issue to main repository.
