### ISSUE TITLE
NMMNH LVB Problems

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#219]
These LVB ages are not defined in the code table, how should they be recorded?

Locality | LVB
-- | --
6419 | To4
8755 | To4
8761 | To4
8763 | To4
8764 | To4
2567 | To5
6412 | To5
8768 | To5
3542 | To6
3544 | To6
3547 | To6
8645 | To6
8646 | To6
8647 | To6
8648 | To6
8649 | To6
8770 | To6

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
The should be Tj#
