### ISSUE TITLE
Custom ID Type for ALMNH

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/data-migration#236]
Hello,

Can someone please create two Custom ID Types for us?  ALMNH History Collection and ALMNH Ethnographic Collection

Also, if I want to designate a specific collection within one of the major collection categories, ie. such as the E.O. Wilson Collection, or the Ralph Chermock Collection,  can I do this or does someone need to create these categories for me?

Thanks!
Mary Beth

**Comment by campmlc** [comment]
Hi Mary Beth, will these be collections in Arctos? Do they or will they
ever have GUIDs, e.g. ALMNH:History? Or is the format for the identifier
just ALMNH History Collection?

**Comment by mbprondzinski** [comment]
Hi Mariel,

We already have the collections name set up by Teresa (ALMNH:EH).  I just want to be able to differentiate between the History  and the Ethnographic.  She did this for us with the three types of Paleo collections and the Geology collection, all of which fall under  ALMNH:ES.

**Comment by Jegelewicz** [comment]
Done.
