### ISSUE TITLE
2. NMMNH Paleo - Create an Arctos Team

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#24]
Follow instructions at [How To Create and Manage Your Arctos Team: Users and Operators](http://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html)

**Comment by lin-fred** [comment]
We're looking to getting our registrar an account. We've made him one, invited him as operator, and then we've given him access:

![image](https://user-images.githubusercontent.com/19802479/55114187-e64b5280-50a6-11e9-8359-509818497792.png)

were mostly wanting him to have access to the transactions. When he logs in he still sees all of the collections in arctos. Is there a way to limit what he sees to just ours? And is there anything else you recommend he have?

**Comment by lin-fred** [comment]
His username is gracebrian btw

**Comment by dustymc** [comment]
URL+Screenshot of "all the collections" please.

**Comment by Jegelewicz** [comment]
> When he logs in he still sees all of the collections in arctos. Is there a way to limit what he sees to just ours? 

You can see everything on the Portals page when logged in, but when he searches, he should only see your specimens. Test that out.

> And is there anything else you recommend he have?

That's probably good for now. He may need Agents added or modified, but if it doesn't happen that often, he could just ask one of you to do that for him.

**Comment by lin-fred** [comment]
This is what I mean by all collections are listed in the search. When he searches it searches all of the portals. Is there a way, other than him only ticking our collections, or looking at one specific portal, to search all of our portals?
![image](https://user-images.githubusercontent.com/19802479/55115764-ea796f00-50aa-11e9-9136-3b34e1fc418b.png)

![image](https://user-images.githubusercontent.com/19802479/55115916-4a701580-50ab-11e9-89f1-93c616871077.png)

**Comment by dustymc** [comment]
Try logging out and back in. We should probably force logout when something changes....

**Comment by lin-fred** [comment]
Yes thank you that worked! I should have known...

Either having a force logout, or having it on the "How to" page would helpful?

**Comment by dustymc** [comment]
I updated http://handbook.arctosdb.org/documentation/users.html

**Comment by Jegelewicz** [comment]
I also added:

> * Before the Operator can make full use of Arctos as you have assigned, they will need to log out of Arctos and log in again.

to the How-To

**Comment by Jegelewicz** [comment]
Added Hannah to the team. Closing as complete.
