### ISSUE TITLE
Bulkloading problem

### ISSUE THREAD

**Issue by byuherpetology** [ArctosDB/data-migration#250]
We are trying to bulkload the records that were lost in the crash and are having trouble.  The records are loading just fine, but then we are having two different problems.  When I go in to approve the records in the browse and edit menu, the records are marked as duplicate catalog numbers. When I search for these same catalog numbers, I get results but the records are blank
<img width="1244" alt="Screen Shot 2020-04-30 at 9 39 34 AM" src="https://user-images.githubusercontent.com/48566837/80731620-6329d680-8ac8-11ea-8bdc-452f77be4864.png">
I did have some records that I was able to approve in the browse and edit menu, but the total number of records in our collection did not change, and when I search for these records I get blank records as above, or records with one field showing but not selectable
<img width="1240" alt="Screen Shot 2020-04-30 at 9 38 59 AM" src="https://user-images.githubusercontent.com/48566837/80731769-940a0b80-8ac8-11ea-8e08-4b4d5b13659e.png">

Any idea what is going wrong?

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/2625

**Comment by ebraker** [comment]
Hi Alison, your records are processing. Sounds like things are just slow but they will go through. 

You can check the status here:
![image](https://user-images.githubusercontent.com/11336485/80732297-59ed3980-8ac9-11ea-9980-28bfe7189f49.png)

**Comment by campmlc** [comment]
We are working on getting a notification of this lag in record loading in
the newsletter.
