### ISSUE TITLE
NMMNH Invert bulkloading issues

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/data-migration#251]
Having this error: 
![image](https://user-images.githubusercontent.com/19802479/81853882-51115480-951a-11ea-80c1-d6ff939eeaf4.png)

with this file:
[1InvertBulkload_4000_5999_attempt.txt](https://github.com/ArctosDB/data-migration/files/4624117/1InvertBulkload_4000_5999_attempt.txt)

**Comment by dustymc** [comment]
<img width="281" alt="Screen Shot 2020-05-13 at 12 17 27 PM" src="https://user-images.githubusercontent.com/5720791/81855248-f1b04600-9513-11ea-9fee-a15a9fb4e234.png">

collection_object_id is NULL - I think you can either delete the column or provide a unique (for that file) integer on each row.

**Comment by lin-fred** [comment]
I normally leave it blank, the 4000 that were uploaded this morning were blank. Has something changed in the last hour?

**Comment by lin-fred** [comment]
Here is one of the ones I uploaded just an hour or two ago:
[InvertBulkload_2000_3999_attempt_completed1.txt](https://github.com/ArctosDB/data-migration/files/4624207/InvertBulkload_2000_3999_attempt_completed1.txt)

**Comment by lin-fred** [comment]
So I deleted the collection_object_id, then re-added it and left the fields null, tried again, now it works

**Comment by dustymc** [comment]
Nope, no recent changes! 

I dug a little deeper, there are unescaped linefeeds in the CSV - it's not valid CSV (and would die with a noprint error if they were properly escaped).

<img width="769" alt="Screen Shot 2020-05-13 at 12 30 51 PM" src="https://user-images.githubusercontent.com/5720791/81856438-a72fc900-9515-11ea-8e6e-1c364494ca6e.png">

<img width="553" alt="Screen Shot 2020-05-13 at 12 31 41 PM" src="https://user-images.githubusercontent.com/5720791/81856495-badb2f80-9515-11ea-824e-cf87251b4d70.png">

**Comment by lin-fred** [comment]
I am getting this error:
![image](https://user-images.githubusercontent.com/19802479/81983432-a1f37c80-95f0-11ea-82a5-eab9aaa96b32.png)

with this file:
[1InvertBulkload_4000_5999_attempt3.txt](https://github.com/ArctosDB/data-migration/files/4630758/1InvertBulkload_4000_5999_attempt3.txt)

**Comment by Jegelewicz** [comment]
You have some non-printing characters or hard returns in the Collection Object Remarks field.

**Comment by lin-fred** [comment]
what's the best way to find them?

**Comment by Jegelewicz** [comment]
Can you put the workbook here (you can attach Excel)

**Comment by lin-fred** [comment]
[InvertBulkload_4000_5999.xlsx](https://github.com/ArctosDB/data-migration/files/4630825/InvertBulkload_4000_5999.xlsx)

**Comment by Jegelewicz** [comment]
That will be in verbatim locality.

**Comment by lin-fred** [comment]
Yes but I can't seem to find out what it is, looked for the x00, trimmed it, but no luck

**Comment by Jegelewicz** [comment]
Hmmmm - are there any terms with diacritics or symbols other than a-z and 0-9?

**Comment by dustymc** [comment]
You can load to bulkloader_stage then

<img width="198" alt="Screen Shot 2020-05-14 at 2 13 02 PM" src="https://user-images.githubusercontent.com/5720791/81986644-0f051300-95ed-11ea-975a-869646d4b0b1.png">

```
select regexp_replace(verbatim_locality, '[^[:print:]]', '[X]') r from bulkloader_stage where regexp_like(verbatim_locality,'[^[:print:]]')
```

PO Guam (US)[X]Mariana Islands 

Or often just look in a text editor - one from ^^up there^^ looks like this:

<img width="262" alt="Screen Shot 2020-05-14 at 2 14 44 PM" src="https://user-images.githubusercontent.com/5720791/81986789-568b9f00-95ed-11ea-9a82-5ca3c641764d.png">

**Comment by Jegelewicz** [comment]
Have you tried using the TRIM() function to remove trailing spaces too?

**Comment by lin-fred** [comment]
Thanks Dusty, I'll run that query or scroll through the notepad text next time.

> Have you tried using the TRIM() function to remove trailing spaces too?
Yes I did

**Comment by Jegelewicz** [comment]
Thanks @dustymc it is in 4261

**Comment by Jegelewicz** [comment]
FWIW, I tried and if you set the format to wrap text for the offending column it will pop out as long as the column is pretty wide.

![image](https://user-images.githubusercontent.com/5725767/81987862-b8e99d00-95f7-11ea-9301-4ebb60d4258e.png)

**Comment by lin-fred** [comment]
![image](https://user-images.githubusercontent.com/19802479/82225101-f6914300-98e1-11ea-920a-78ee6bf5ff6c.png)
Does anyone know what this error means?

**Comment by Jegelewicz** [comment]
Column U doesn't have a heading? Looks like it should be VERBATIM_LOCALITY?

**Comment by dustymc** [comment]
insert into bulkloader_stage ( ,ACCN,AT

You have a NULL header.

**Comment by lin-fred** [comment]
Thanks!

**Comment by lin-fred** [comment]
Mollusc bulkloading is done, thanks for everyone's help!
