### ISSUE TITLE
NMMNH - "Non-tissued" mammals

### ISSUE THREAD

**Issue by lin-fred** [ArctosDB/data-migration#256]
Thread for comments for non-tissued NMMNH mammal upload

**Comment by lin-fred** [comment]
I have hind foot length attributes, There are two options: hind foot with claw and hind foot without claw

I don't know how these legacy data were measured. any idea as to what to upload them as?

**Comment by jldunnum** [comment]
Hey Lindsey,
North American mammalogists used hind foot with claw

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by ebraker** [comment]
Measurements likely include claw for North American material. I can't remember what reference, but this is a standard, whereas in Europe it is reversed. Perhaps include a note in attribute remarks if unsure, 'methodology not recorded but hindfoot measurement presumed to include claw.'

**Comment by jldunnum** [comment]
Ha beat you by about three seconds Emily😉!

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by ebraker** [comment]
Ha ha, we'll have to review the tapes @jldunnum  ;)

**Comment by lin-fred** [comment]
Thank you both! 

I think I will include the disclaimer in the remarks just to be on the safe side

**Comment by jldunnum** [comment]
Can also look at the collector information, for example if Dave Hafner collected it we would know it was by our standards including claw.

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by cjconroy** [comment]
Many collectors annotated measurements with c.u. (cum unguis) or s.u. (sin unguis), so at some point, some data could be rectified. But, collectors and preparators have been inconsistent. 
The other issue that is very similar is the ear. Ear from notch is common now, but in the past some North American collectors took ear from crown.

**Comment by lin-fred** [comment]
@dustymc can you decipher this for me:

![image](https://user-images.githubusercontent.com/19802479/83448148-c207a600-a40e-11ea-9eb3-dda4f4bf8936.png)

**Comment by dustymc** [comment]
I need more context

**Comment by lin-fred** [comment]
here is the text:
[Mammals without tissue1.txt](https://github.com/ArctosDB/data-migration/files/4713253/Mammals.without.tissue1.txt)

**Comment by dustymc** [comment]
<img width="363" alt="Screen Shot 2020-06-01 at 1 36 00 PM" src="https://user-images.githubusercontent.com/5720791/83452048-dcd91b00-a40c-11ea-8d66-df9edf2bef15.png">

**Comment by lin-fred** [comment]
Ack thanks, I see the wrong header number, but was that the issues at position 1549?

**Comment by lin-fred** [comment]
At some point in the past I remember being able to enter in [13] for a measurement. Am I remembering incorrectly or is it different now?

**Comment by Jegelewicz** [comment]
With the brackets? Only in "unformatted measurements" which is free text. I'm pretty sure the lengths and such are all numeric only.
