### ISSUE TITLE
5500 is a placeholder locality for un-georeferenced specimens in the Rousseau Flower collection.

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#261]
> > 5500 is a placeholder locality for un-georeferenced specimens in the Rousseau Flower collection.
> 
> @Nicole-Ridgwell-NMMNHS how shall I handle this? I suggest higher geography = North America, United States and specific locality = "No specific locality recorded."

I am fine with that solution.

_Originally posted by @Nicole-Ridgwell-NMMNHS in https://github.com/ArctosDB/data-migration/issues/130#issuecomment-596616295_

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS as I have been working on the records for localities 5400-12345, I have found that for locality 5500, the specific locality information is in the Access database in the remarks field which I have been transcribing into the Collection Object Remark field in Arctos. This means that the locality for these specimens will be public, although in an odd place. Should we create a [mask record encumbrance](https://arctos.database.museum/info/ctDocumentation.cfm?table=CTENCUMBRANCE_ACTION#mask_record) for all of the records in locality 5500 to keep them out of the public view?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> create a mask record encumbrance

No, lets not worry about encumbering those. They're all invertebrates collected many decades ago, so I am not worried about them. 

> I suggest higher geography = North America, United States and specific locality = "No specific locality recorded."

I'm not certain that they are all North America. When we were going through that collection looking for lost specimens from Svalbard (which we didn't find), there were specimens from Europe that I think were also under that locality.

**Comment by Jegelewicz** [comment]
> I'm not certain that they are all North America. When we were going through that collection looking for lost specimens from Svalbard (which we didn't find), there were specimens from Europe that I think were also under that locality.

Yeah, there are definitely things from Europe in there, but most seem to be from North America. We could also use "no higher geography". Currently the locality is entered with "North America, United States".

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
My preference is "no higher geography".

**Comment by Jegelewicz** [comment]
Done!
