### ISSUE TITLE
4. NMMNH Inv - Accessions

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#30]
Read the documentation about [Accessions](http://handbook.arctosdb.org/documentation/accession.html)

If you have legacy Accession data to enter, they can be entered individually using [these instructions](http://handbook.arctosdb.org/how_to/How-to-Create-an-Accession.html) or they can be created in bulk using the [Accession Bulkload Tool](http://arctos.database.museum/tools/BulkloadAccn.cfm) **NEED HOW TO**.

**Comment by lin-fred** [comment]
; ACCN is invalid

1984.001
1984.006
1984.008
1991.022
1999.034
2007.001
2011.008

**Comment by lin-fred** [comment]
Is there a mineral portal yet? Apparently 1984.001 is classified as a mineral acc, @Nicole-Ridgwell-NMMNHS can you check your mineral database and confirm there are minerals in it? And if so how should we go about this? Because I need to link up some of my specimens to it

**Comment by Jegelewicz** [comment]
NMMNH:Geol is the portal - there is no accession with that number created though.

**Comment by lin-fred** [comment]
1984.001 --> added accession into Minerals, linked invertebrates [NMMNH:Geol]1984.001
1984.006 --> [NMMNH:Mamm]1984.006
1984.008 --> [NMMNH:Mamm]1984.008
1991.022 --> was going to do [NMMNH:Ento]1991.022, but there are 358 inverts, and only 4 insects with this accession, so Ill be switching it around. Created NMMNH:Inv 1991.022, and will migrate the 4 insects into that one and delete NMMNH:Ento 1991.022
1999.034
2007.001
2011.008

**Comment by lin-fred** [comment]
I went to NMMNH:Ento:6079, clicked to edit Accession, searched for the NMMNH:Inv 1991.022, clicked add, it now says its in that accession, but when I try and pull up specimens in NMMNH:Inv 1991.022 it still show there are none? Does it just take awhile? Or did I do it wrong?

**Comment by Jegelewicz** [comment]
I t does take a while - if it hasn't worked by tomorrow, let us know.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
1984.001 --> added accession into Minerals, linked invertebrates [NMMNH:Geol]1984.001

Thanks, I'll update the record with any additional data once I get to adding the Mineral accessions.

**Comment by lin-fred** [comment]
2001.005 - a fossil accession. will put these specimens under [NMMNH:Paleo]2001.005

**Comment by lin-fred** [comment]
1984.007

**Comment by lin-fred** [comment]
1984.009
1998.116
1996.016
