### ISSUE TITLE
4. NMMNH Herb - Accessions

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#32]
Read the documentation about [Accessions](http://handbook.arctosdb.org/documentation/accession.html)

If you have legacy Accession data to enter, they can be entered individually using [these instructions](http://handbook.arctosdb.org/how_to/How-to-Create-an-Accession.html) or they can be created in bulk using the [Accession Bulkload Tool](http://arctos.database.museum/tools/BulkloadAccn.cfm) **NEED HOW TO**.

**Comment by lin-fred** [comment]
I would like to close this but I can't seem to?

**Comment by lin-fred** [comment]
Also it seems I am not assigned to a lot of the biology related NMMNH stuff, can that get updated soon? Much appreciated!

**Comment by Jegelewicz** [comment]
Lindsey,

It looks like you have access to all of them:

![image](https://user-images.githubusercontent.com/5725767/62796387-60003d80-ba96-11e9-83cd-8b3b424d2b51.png)

Can you give me a specific example of what is happening?

**Comment by lin-fred** [comment]
Oh I mean here on Github~

**Comment by Jegelewicz** [comment]
Try now...

**Comment by lin-fred** [comment]
Nope still can't close it, and also can't move around the tile cards in the project. The close button is next to the comment button right?

**Comment by Jegelewicz** [comment]
Yep. Let me see what I've missed.

**Comment by Jegelewicz** [comment]
Well, GitHub is doing something because I am unable to view any of the projects. See if you can close this though.

**Comment by lin-fred** [comment]
Yes I can close it now
