### ISSUE TITLE
4. NMMNH Mammals - Accessions

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#35]
Read the documentation about [Accessions](http://handbook.arctosdb.org/documentation/accession.html)

If you have legacy Accession data to enter, they can be entered individually using [these instructions](http://handbook.arctosdb.org/how_to/How-to-Create-an-Accession.html) or they can be created in bulk using the [Accession Bulkload Tool](http://arctos.database.museum/tools/BulkloadAccn.cfm) **NEED HOW TO**.

**Comment by lin-fred** [comment]
1995.012 - paleo accession [NMMNH:Paleo]1995.012
1999.034 - invert accession [NMMNH:Inv]1999.034
2005.027
2006.022
