### ISSUE TITLE
6. NMMNH Ento - Taxonomy (Classifications)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#40]
Read the [Taxonomy](http://handbook.arctosdb.org/documentation/taxonomy.html) documentation

For any names that were added in the previous data migration step, there will not be a related classification in any of the local Arctos taxonomy sources. For a small number of new names, these can be created manually by following the instructions in [How To Create Taxa](http://handbook.arctosdb.org/how_to/How-to-Create-Taxa.html). To create a large number of classifications, use the [Bulkload Taxonomy Classifications Tool](http://arctos.database.museum/tools/BulkloadClassification.cfm)

**Comment by lin-fred** [comment]
For adding taxonomy, will I need to create a list and send to someone? I don't seem to have the authority to add taxonomy, which is fine, I just need to know what to do! Thanks!

**Comment by Jegelewicz** [comment]
Lindsey,

Probably easiest to just send me the file. You can zip up csv and post it here or just email me an excel file.
