### ISSUE TITLE
6. NMMNH Herb - Taxonomy (Classifications)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#42]
Read the [Taxonomy](http://handbook.arctosdb.org/documentation/taxonomy.html) documentation

For any names that were added in the previous data migration step, there will not be a related classification in any of the local Arctos taxonomy sources. For a small number of new names, these can be created manually by following the instructions in [How To Create Taxa](http://handbook.arctosdb.org/how_to/How-to-Create-Taxa.html). To create a large number of classifications, use the [Bulkload Taxonomy Classifications Tool](http://arctos.database.museum/tools/BulkloadClassification.cfm)

**Comment by lin-fred** [comment]
For Dichelostemma capitatum subsp. pauciflorum, in Arctos it's only as Dichelostemma capitatum pauciflorum, without the subsp.

And it seems its missing some of its Classification data. What should I do about using this/changing it?

**Comment by dustymc** [comment]
Oh my...

http://arctos.database.museum/taxonomy.cfm?taxon_name=Dichelostemma&taxon_term=&term_type=&source=&common_name= is all kinds of "interesting...."

http://arctos.database.museum/name/Dichelostemma%20capitatum%20pauciflorum is not used...

<img width="221" alt="Screen Shot 2019-08-13 at 12 28 42 PM" src="https://user-images.githubusercontent.com/5720791/62971137-e7ff8380-bdc5-11e9-8071-0c484005413d.png">

and given the context I'd probably assume it's just wrong and can be changed, which you should be able to do. If it was used, or if there really are various names that vary by infraspecific rank, both can be added.

The general guidance on classifications is "don't mess with the fundamental nature of the data without talking to the other collections" - if you want to change this to a jellyfish (and someone's using it), you should consult with them. If you just want to fill in some blanks, you can probably just go ahead. (Any collection can split classifications to avoid that.)

**Comment by lin-fred** [comment]
Because it's not used, are you suggesting I delete the classification that it's attached to, edit the name to include subsp. then add back in the classification? Is that how editing these work when it's not in use?

**Comment by Jegelewicz** [comment]
@lin-fred that is what I would do.

**Comment by dustymc** [comment]
>delete the classification

That step isn't necessary, but may be easier than editing it anyway.
