### ISSUE TITLE
5. NMMNH Herb - Identifications (Taxon Names)

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#43]
Read the [Taxonomy](http://handbook.arctosdb.org/documentation/taxonomy.html) documentation

Determine if you need to add names to the Taxon Names code table. Create a list of all scientific names used to identify your specimens. This list should be in a single column of an Excel spreadsheet with the column header **scientific_name** and saved as a CSV. Use this file in the [Scientific Name Checker Tool](http://arctos.database.museum/DataServices/SciNameCheck.cfm) to help you determine what names you need to correct in your data (misspellings, etc.) and which names you need to add to Arctos. Isolate the names that you need to add in a new Excel file with the column header **scientific_name** and save the file as a CSV. Use this file in the [Bulkload Taxonomy Names Tool](http://arctos.database.museum/tools/BulkloadTaxonomy.cfm) to add any names that are currently not in Arctos. This will allow you to use the names, but does not provide related classifications.

**Comment by lin-fred** [comment]
I have possibly 59 taxon to add for plants/fungi. I have put the excel sheet in the NMMNHS dropbox folder  titled BotanyArctosTaxonomyToAdd. There are links to each that indicate it's a valid species, although some may have a question mark if I was unsure. Someone will have to put them into Arctos for us?

**Comment by Jegelewicz** [comment]
Lindsey,

I can do it, but would you like to be able to add them yourself? If so, I can give you permissions and you can use the Bulkload Taxonomy Names Tool to add the names, then the [Bulkload Taxonomy Classifications Tool](http://arctos.database.museum/tools/BulkloadClassification.cfm) to load the classifications - or you can [create them one-by-one using the tools available](http://handbook.arctosdb.org/how_to/How-to-Create-Taxa.html).

**Comment by lin-fred** [comment]
Yes, if you don't mind giving me permission I can do it!

**Comment by Jegelewicz** [comment]
OK - you should be able to manage taxonomy. Before you do anything though, please read the following.

[Taxonomy Documentation](http://handbook.arctosdb.org/documentation/taxonomy.html)
[How to Create Taxa](http://handbook.arctosdb.org/how_to/How-to-Create-Taxa.html)
[How to Edit Taxa](http://handbook.arctosdb.org/how_to/How_to_Edit_Taxa.html)
[How to Manage Taxonomic Classifications](http://handbook.arctosdb.org/how_to/How-to-manage-taxonomic-classifications.html)

It would also be really good for you to watch the [Taxonomy Webinar](https://www.youtube.com/watch?v=1AMQ8SfrXiU&feature=youtu.be) if you haven't already seen it.

Let me know if you have any questions!

**Comment by lin-fred** [comment]
Is adding Andropogon gerardii the same process as adding Andropogon gerardii var. gerardii?

**Comment by lin-fred** [comment]
Also, Bolbitius tener is currently not valid and is now Conocybe apala, and neither are in Arctos. Is there a way for us to capture this change while migrating in? Should I upload the specimen as B. and then change it to C.? Or can I upload it as C. and then add in that it was originally B.?

**Comment by Jegelewicz** [comment]
> Is adding Andropogon gerardii the same process as adding Andropogon gerardii var. gerardii?

Yep!

**Comment by Jegelewicz** [comment]
> Also, Bolbitius tener is currently not valid and is now Conocybe apala, and neither are in Arctos. Is there a way for us to capture this change while migrating in? Should I upload the specimen as B. and then change it to C.? Or can I upload it as C. and then add in that it was originally B.?

1. Put both names in Arctos
2. Create a relationship between them by making them synonyms (Edit one of the names and add "synonym of" the other name).
3. Add both classifications
4. In the Bolbitius tener classification metadata, add the term "taxon status" and enter "invalid" and add the term "preferred name" and enter "Conocybe apala".
5. In the Conocybe apala classification metadata add the term "taxon status" and enter "valid"

You can load the record initially with the original ID, then add the second accepted ID with the Nature of ID "revised taxonomy"

If this is all clear as mud, just let me know!

**Comment by lin-fred** [comment]
Thanks, that is clear!

Although am I able to upload it as the valid C. and then indicate its original identification was the now invalid B.? Or does it have to be in the order you described above?

**Comment by Jegelewicz** [comment]
Nope, you can do it in any order. Just beware that if you add the invalid second, you will need to re-accept the valid id as the lest entered id defaults to "valid". It's just a click of a button.

**Comment by lin-fred** [comment]
I have some species that I can't find much information for, like:
Polyporus albaluteus

Is it possible to add the taxon without the classification? Or should I upload it as Polyporus, and add some remarks into the the actual specimen page?

**Comment by dustymc** [comment]
>Is it possible to add the taxon without the classification?

Yes, but it's likely to create more work (maybe lots more work) later on. Taxonomy Committee, advize please...

>Polyporus albaluteus

How sure of that being a real name are you? If fails "the Google test"...


<img width="389" alt="Screen Shot 2019-08-19 at 10 26 14 AM" src="https://user-images.githubusercontent.com/5720791/63285984-d148a900-c26b-11e9-8087-91fd401ee4e3.png">

... which absolutely isn't definitive, but makes me have some serious doubts.

>upload it as Polyporus

If there's any certainty regarding the name, I'd use the "A {string}" formula and a known-real taxon - the bulkloader (http://handbook.arctosdb.org/documentation/bulkloader.html#taxonomy) will accept ``Polyporus {Polyporus albaluteus}`` which will display Polyporus albaluteus with a link to Polyporus.

>remarks

Those are useful for clarification and such, but not a substitute for an identification.

**Comment by lin-fred** [comment]
Thank you Dusty, that is helpful!

I am uncertain of the name. We have three fungi specimens that have no original documentation other than the catalog page, and have species names that are odd. At this point an expert will need to look at them, but in the meantime, I think entering them in with the string formula would be best?

**Comment by Jegelewicz** [comment]
Using the string formula keeps the names out of Arctos names and reduces the likelihood that someone else will use them. I like that plan!

**Comment by campmlc** [comment]
Good solution!

**Comment by lin-fred** [comment]
Great!
