### ISSUE TITLE
ALMNH ES PB - Locality Ids

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#66]
@dustymc when the Paleobotany specimens for ALMNH were bulkloaded, all of the locality IDs were put in the locality. They belong in the Locality ID other identifier. Any way we can fix them without me going one-by-one?

Here is an example: http://arctos.database.museum/guid/ALMNH:ES:14555

**Comment by dustymc** [comment]
Here are the data. 

[temp_amnh_loc(1).csv.zip](https://github.com/ArctosDB/data-migration/files/3429749/temp_amnh_loc.1.csv.zip)

They could be cleaned up and added as locality name fairly easily too.

```

UAM@ARCTOS> select locality_id,locid from temp_amnh_loc group by locality_id,locid  order by locality_id,locid ;

LOCALITY_ID
-----------
LOCID
------------------------------------------------------------------------------------------------------------------------
   10906179
AWk-1

   10906184
AWk-2

   10906205
AWk-1

   10906242
Bad Schonborn District

   10906247
AGr-17

   10906249
Duttweiler District

   10906279
AWk-2
```

**Comment by Jegelewicz** [comment]
OK, cool. I only need to change a few localities and then I can bulkload the Other IDs.

Thanks!
