### ISSUE TITLE
ALMNH ES PB - Accessions

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#67]
I have removed everything from the "[ALMNH:ES:0000](http://arctos.database.museum/editAccn.cfm?action=edit&transaction_id=21118853)" accession except a few remaining specimens which do not have a PB or PV number. Once we have those, they can be placed in the correct accession.

**Comment by Jegelewicz** [comment]
@mbprondzinski In order to be consistent, I have created all of the appropriate PB accession numbers and associated specimens with them. The accessions were created as skeletons and I will add any information I am able to glean from the specimens to fill them out better. Feel free to edit them as well if you like.

More important are the 4 specimens left in the "[0000](http://arctos.database.museum/editAccn.cfm?action=edit&transaction_id=21118853)" accession. If we can get PB or PV numbers for them, I can get them added to the correct accession(s).

Thanks!

**Comment by mbprondzinski** [comment]
Hi Teresa,

Just saw this...  I will get to it asap.  I am running into a major problem with the Invert Paleo.  None of the records in the database coincide with the 1985 Accessions assigned (!)  I'm not sure what to do about it.  I will have to speak with John, but we are just about to entertain the Paleo candidates so he is busy preparing for that.

Mary Beth
________________________________

**Comment by Jegelewicz** [comment]
Mary Beth,

No rush  on the botany accessions.

As for the inverts, bummer. I'm not sure I can help with that, but if you think I can, please let me know!

Good luck!
