### ISSUE TITLE
Creating an Accession

### ISSUE THREAD

**Issue by byuherpetology** [ArctosDB/data-migration#73]
I am trying to create a new accession, following http://handbook.arctosdb.org/how_to/How-to-Create-an-Accession.html  .  Under manage data, I do not have a transactions option.  Do I not have permission to create an accession, or am I looking in the wrong place?

**Comment by Jegelewicz** [comment]
I gave you permissions to manage transactions. Before you use the How-To, please also read the [Accessions Documentation](http://handbook.arctosdb.org/documentation/accession.html) and let me know if you have any questions.

**Comment by byuherpetology** [comment]
Yes, I do have one question; Is an accession# required for all specimen records?  I haven’t found this in the documentation but that is what it looks like on the data entry form.

**Comment by campmlc** [comment]
Yes, an accession number is required, but if you choose not to create
individual accessions or do not have that info available, you can create a
legacy accession (e.g. 0000.00.Herp), that can be used instead. You can
later move groups of specimens to other accessions as needed as you create
them or find the documentation.

**Comment by mkoo** [comment]
that's a good tip for the handbook!

**Comment by byuherpetology** [comment]
Exactly what I needed, thank you.
