### ISSUE TITLE
duplicate museum number

### ISSUE THREAD

**Issue by byuherpetology** [ArctosDB/data-migration#77]
As I have been playing with the data entry form it appears that Arctos allows you to duplicate numbers within a collection.  Is there a way to prohibit duplication of a collection number or is this something that needs to be caught in the approval process?

Also, is this the right forum to ask such a simple question?  I hate to clog things up with minutia.

**Comment by dustymc** [comment]
The data entry form writes to the bulkloader (http://handbook.arctosdb.org/documentation/bulkloader.html), which has few constraints. Duplicate catalog numbers will not load to Arctos Proper.

https://github.com/ArctosDB/arctos/issues is a bit more visible, but here is fine for "getting started" questions as well. PLEASE continue to ask any questions you have - that leads to better documentation, helps us understand user's needs, leads other users to things they weren't aware of, etc. And answering questions is a lot more fun than dealing with mangled-up data after the fact!

**Comment by Jegelewicz** [comment]
> here is fine for "getting started" questions as well. PLEASE continue to ask any questions you have - that leads to better documentation, helps us understand user's needs, leads other users to things they weren't aware of, etc. And answering questions is a lot more fun than dealing with mangled-up data after the fact!

YES! Ask ALL of your questions here!!! :-)
