### ISSUE TITLE
7. NMMNH Herb - Higher Geography

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#79]
Higher geography is a combination of terms delineating geopolitical units and is controlled by a [code table](http://arctos.database.museum/geography.cfm). To ensure that your specimens are searchable and that your data will load properly, it is important to make sure that higher geography is extracted from locality as HIGHER_GEOG in your migration data and included in the code table. Read the [Higher Geography documentation](http://handbook.arctosdb.org/documentation/higher-geography.html), and ensure that the higher geography you are planning to migrate is included in the code table. If you need new terms added, contact your mentor or post issues to [GitHub](https://github.com/ArctosDB/arctos/issues).

**Comment by lin-fred** [comment]
@Jegelewicz It seems there are higher geographies I need added to arctos for me to upload the next plant batch. Are you able to add them? Let me know if you need something.

North America, United States, New Mexico, Union County, Kiowa National Grasslands
North America, United States, Colorado, Huerfano County, San Isabel National Forest
North America, United States, New Mexico, Eddy County, Lincoln National Forest
North America, United States, New Mexico, Lincoln County, Lincoln National Forest
North America, United States, New Mexico, Mora County, Carson National Forest
North America, United States, New Mexico, Mora County, Coyote Creek State Park
North America, United States, New Mexico, Mora County, Santa Fe National Forest
North America, United States, New Mexico, Rio Arriba County, Carson National Forest
North America, United States, New Mexico, Rio Arriba County, Santa Fe National Forest
North America, United States, New Mexico, Sandoval County, Cibola National Forest
North America, United States, New Mexico, Torrance County, Cibola National Forest
North America, United States, New Mexico, Union County, Clayton Lake State Park

**Comment by Jegelewicz** [comment]
I think I got them all - let me know if you need any more.

**Comment by lin-fred** [comment]
one more it seems:

North America,   United States, Wyoming, Teton County, Yellowstone National Park

**Comment by Jegelewicz** [comment]
Added.

**Comment by lin-fred** [comment]
Some more it seems, thank you! I'll be better about getting them all for the next batch

North America,   United States, New Mexico, Mora County, Carson National Forest
North America,   United States, New Mexico, Harding County, Kiowa National Grassland

**Comment by Jegelewicz** [comment]
Added!

**Comment by lin-fred** [comment]
Next batch:

North America, Canada, Alberta, Kootenay National Park
North America, United States, Arizona, Cochise County, Coronado National Forest
North America, United States, Arizona, Pima County, Cabeza Prieta National Wildlife Refuge
North America, United States, Arizona, Pima County, Coronado National Forest
North America, United States, Arizona, Pinal County, Tonto National Forest
North America, United States, New Mexico, Catron County, Apache-Sitgreaves National Forest
North America, United States, New Mexico, Colfax County, Cimarron Canyon State Park
North America, United States, New Mexico, Eddy County, Brantley Lake State Park
North America, United States, New Mexico, Hidalgo County, Coronado National Forest
North America, United States, Wyoming, Park County, Gallatin National Forest
North America, United States, Wyoming, Teton County, Gallatin National Forest

And is this one a feature? 

North America, United States, New Mexico, Grant County, Redrock State Wildlife Experimental Area

**Comment by Jegelewicz** [comment]
> North America, Canada, Alberta, Kootenay National Park

[Kootenay National Park](https://en.wikipedia.org/wiki/Kootenay_National_Park) is a national park located in southeastern British Columbia, Canada

This one requires a decision - either use Alberta OR use North America, Canada, British Columbia, Kootenay National Park.

**Comment by Jegelewicz** [comment]
Arctos has been down.
/remind me to add these tomorrow

North America, United States, Arizona, Cochise County, Coronado National Forest
North America, United States, Arizona, Pima County, Cabeza Prieta National Wildlife Refuge
North America, United States, Arizona, Pima County, Coronado National Forest
North America, United States, Wyoming, Park County, Gallatin National Forest
North America, United States, Wyoming, Teton County, Gallatin National Forest
North America, United States, New Mexico, Grant County, Redrock State Wildlife Experimental Area

**Comment by Jegelewicz** [comment]
> North America, United States, New Mexico, Grant County, Redrock State Wildlife Experimental Area

Is entered as:

North America, United States, New Mexico, Grant County, NMDGF, Red Rock Wildlife Management Area

**Comment by lin-fred** [comment]
based on the specific locality, lets use:

North America, Canada, British Columbia, Kootenay National Park

**Comment by dustymc** [comment]
Wutsa NMDGF and why's it there?

**Comment by lin-fred** [comment]
> Wutsa NMDGF and why's it there?

New Mexico Department of Game and Fish, which I assume shouldn't be in a higher geography. Let me know if it gets changed so I can update my sheet

**Comment by lin-fred** [comment]
My last batch for the plants:

North America, United States, Arizona, Yavapai County, Coconino National Forest
North America, United States, Arizona, Yavapai County, Kaibab National Forest
North America, United States, New Mexico, Chaves County, Bottomless Lakes State Park
North America, United States, New Mexico, Cibola County, Bluewater Lake State Park
North America, United States, New Mexico, De Baca County, Sumner Lake State Park
North America, United States, New Mexico, Dona Ana County, Leasburg Dam State Park
North America, United States, New Mexico, Eddy County, Brantley Lake State Park
North America, United States, New Mexico, Grant County, City of Rocks State Park
North America, United States, New Mexico, Lincoln County, Valley of Fires Recreation Area
North America, United States, New Mexico, Luna County, Rockhound State Park
North America, United States, New Mexico, Otero County, Oliver Lee State Park
North America, United States, New Mexico, Quay County, Ute Lake State Park
North America, United States, New Mexico, Rio Arriba County, Navajo Lake State Park
North America, United States, New Mexico, Roosevelt County, Oasis State Park
North America, United States, New Mexico, San Juan County, Navajo Lake State Park
North America, United States, New Mexico, Sierra County, Caballo Lake State Park
North America, United States, New Mexico, Sierra County, Percha Dam State Park

**Comment by Jegelewicz** [comment]
> Wutsa NMDGF and why's it there?

It's a state management area and feature - "NMDGF, Red Rock Wildlife Management Area". There are quite a few of these - [see](http://www.wildlife.state.nm.us/conservation/state-game-commission-lands/) I figured putting the "NMDGF" in front of each would help sort them in the code table. Is the comma a problem? I could take it out.

**Comment by Jegelewicz** [comment]
Also thinking that New Mexico state parks should start with NM as there could easily be state parks in other states with the exact same name...

**Comment by lin-fred** [comment]
But even if they have the same name they are organized under new mexico already? Just as there are counties that have the same name in several states? Like Pike County, Arkansas and Pike County, Alabama. Are same name features different than same name counties?

**Comment by Jegelewicz** [comment]
> But even if they have the same name they are organized under new mexico already? Just as there are counties that have the same name in several states? Like Pike County, Arkansas and Pike County, Alabama. Are same name features different than same name counties?

Yes! FEATURES operate differently and are set up in their own [code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=CTFEATURE), then are associated with the appropriate remaining higher geography. This is how we show that Coronado National Forest is THE SAME Coronado National Forest across all the counties involved. Pike County does not exist anywhere on its own, only in association with either Arkansas or Alabama.

**Comment by Jegelewicz** [comment]
I'm going to take this issue to the Arctos repository - I need input from others.

**Comment by Jegelewicz** [comment]
> North America, United States, New Mexico, Grant County, Redrock State Wildlife Experimental Area

Is entered as:

North America, United States, New Mexico, Grant County, Red Rock Wildlife Management Area

**Comment by Jegelewicz** [comment]
> North America, United States, New Mexico, Otero County, Oliver Lee State Park

created as

North America, United States, New Mexico, Otero County, Oliver Lee Memorial State Park

**Comment by Jegelewicz** [comment]
OK, think I got them all! Let me know if I missed any.

**Comment by lin-fred** [comment]
Looks like I'm still missing some here and there from the previous lists that got kicked back:


North America, United States, Wyoming, Teton County, Gallatin National Forest
North America, United States, New Mexico, Colfax County, Cimarron Canyon State Park
North America, United States, New Mexico, Catron County, Apache-Sitgreaves National Forest
North America, United States, Arizona, Pinal County, Tonto National Forest

and then what I was using for our one unknown locality:

no higher geography

from this documentation: https://handbook.arctosdb.org/documentation/higher-geography.html

**Comment by Jegelewicz** [comment]
> North America, United States, Wyoming, Teton County, Gallatin National Forest

It appears there is no such place. Gallatin National Forest is only located in Montana and South Dakota https://www.fs.usda.gov/main/custergallatin/about-forest

**Comment by Jegelewicz** [comment]
> and then what I was using for our one unknown locality:
> 
> no higher geography

It should be "no higher geography recorded"

I'll update documentation.

**Comment by Jegelewicz** [comment]
The rest are done!

**Comment by lin-fred** [comment]
> > and then what I was using for our one unknown locality:
> > no higher geography
> 
> It should be "no higher geography recorded"
> 
> I'll update documentation.

Without a period at the end like this one?:

No specific locality recorded.

**Comment by Jegelewicz** [comment]
No period. - ah, the inconsistency of it!
