### ISSUE TITLE
7. NMMNH Ento - Higher Geography

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/data-migration#81]
Higher geography is a combination of terms delineating geopolitical units and is controlled by a [code table](http://arctos.database.museum/geography.cfm). To ensure that your specimens are searchable and that your data will load properly, it is important to make sure that higher geography is extracted from locality as HIGHER_GEOG in your migration data and included in the code table. Read the [Higher Geography documentation](http://handbook.arctosdb.org/documentation/higher-geography.html), and ensure that the higher geography you are planning to migrate is included in the code table. If you need new terms added, contact your mentor or post issues to [GitHub](https://github.com/ArctosDB/arctos/issues).

**Comment by lin-fred** [comment]
We have a Higher geography that is needed:
https://en.wikipedia.org/wiki/Arcadia

I am unsure where the region fits into, but I'm assuming it's something like this:
Europe, Greece, Arcadia

@Jegelewicz Thanks!

**Comment by Jegelewicz** [comment]
Added as 

Europe, Greece, Peloponnese, Arcadia

**Comment by lin-fred** [comment]
Another one is
Asia, India, Madras

But it seems its also called Chennai https://en.wikipedia.org/wiki/Chennai

**Comment by lin-fred** [comment]
I have a few more, hopefully this is it! Some of them I don't really know what they are supposed to be.....so we might have to do more research...

South America, Brazil, Nova Teutonia
North America, Canada,Ontario, Manning District
Europe,	Sweden, Torne, Lappmark Co.
Europe, Sweden, Tess., Bedveffo County

**Comment by Jegelewicz** [comment]
- Asia, India, Madras = Asia, India, Tamil Nadu (with Madras in specific locality)
From the Wikipediea page: Chennai, also known as Madras (the official name until 1996), is the **capital of the Indian state of Tamil Nadu**. Cities don't belong in higher geography.

- South America, Brazil, Nova Teutonia = South America, Brazil, Santa Catarina (with Nove Teutonia in the specific locality)
There is no wiki for Nove Teutonia, but I did find this [site that says it is in Santa Catarina](http://www.tageo.com/index-e-br-v-26-d-m925395.htm)

- North America, Canada,Ontario, Manning District = North America, Canada, Ontario (with Manning District in specific locality)
I can't find this anywhere! See the [list of census divisions of Ontario](https://en.wikipedia.org/wiki/List_of_census_divisions_of_Ontario)

- Europe, Sweden, Torne, Lappmark Co. = Europe, Sweden (with Torne, Lappmark Co. in specific locality)
I can't find either Torne or Lappmark Co. See the [list of Counties of Sweden](https://en.wikipedia.org/wiki/Counties_of_Sweden). The [Torne](https://en.wikipedia.org/wiki/Torne_(river)) is a river in Sweden though.

- Europe, Sweden, Tess., Bedveffo County = Europe, Sweden (with Tess., Bedveffo County in specific locality)
See above.

**Comment by lin-fred** [comment]
Thank you Thank you!

Another tricky one, It's in arctos, but I don't know which version to use. 

Asia, Philippines, Mindanao

When I look up Mindanao, Arctos comes up with all sorts of options

**Comment by Jegelewicz** [comment]
If you don't know the state, then use:
Asia, Philippines, Philippine Islands, Mindanao

This is the entire island of Mindanao

**Comment by lin-fred** [comment]
I'm looking at Puerto Rico, and I can't seem to find one that has just Puerto Rico. Also, there seems to be some that have different continents? @Jegelewicz

**Comment by Jegelewicz** [comment]
Puerto Rico - if you don't know anything else (county, etc.) use "West Indies, United States, Puerto Rico, Greater Antilles"

Indonesia  - use "Asia, Indonesia, Indonesian Archipelago"

**Comment by lin-fred** [comment]
Ah ok! Thanks for the clarification!

**Comment by lin-fred** [comment]
I have one that is Asia, Indonesia, West Papua with the Padaido Islands. Do you know what this would fall under?

**Comment by Jegelewicz** [comment]
> Asia, Indonesia, West Papua with the Padaido Islands

I think "Asia, Cenderawasih Bay, Indonesia, Papua, Ambai Islands" makes sense. See https://en.wikipedia.org/wiki/Ambai_Islands

**Comment by lin-fred** [comment]
Asia, Thailand, Phrae Province?

Asia, Thailand, Chiangmai Province, San Sai District - is the district a specific locality? https://en.wikipedia.org/wiki/San_Sai_District

**Comment by Jegelewicz** [comment]
added

Asia, Thailand, Phrae Province
Asia, Thailand, Chiang Mai Province, San Sai District
